import { threadCardDataType } from "@/types";

export const threadCardData: threadCardDataType[] = [
	{
		id: "1",
		title: "What is Next Js? How does it work?",
		tag: ["React", "Next.Js"],
		time: "3 minutes",
		like: "1.3K",
		comment: "1K",
		view: "1M",
	},
	{
		id: "2",
		title: "Understanding React Hooks: useState and useEffect",
		tag: ["React", "JavaScript"],
		time: "5 minutes",
		like: "2.1K",
		comment: "800",
		view: "1.5M",
	},
	{
		id: "3",
		title: "Building RESTful APIs with Node.js and Express",
		tag: ["Node.js", "Express.js", "API"],
		time: "8 minutes",
		like: "1.8K",
		comment: "650",
		view: "1.2M",
	},
	{
		id: "4",
		title: "CSS Grid vs. Flexbox: When to Use Which?",
		tag: ["CSS", "Frontend"],
		time: "4 minutes",
		like: "950",
		comment: "300",
		view: "800K",
	},
	{
		id: "5",
		title: "State Management in React: Redux vs. Context API",
		tag: ["React", "Redux"],
		time: "7 minutes",
		like: "1.5K",
		comment: "500",
		view: "1.1M",
	},
	{
		id: "6",
		title: "Deploying Next.js Applications to Vercel",
		tag: ["Next.Js", "Deployment", "Vercel"],
		time: "6 minutes",
		like: "1.2K",
		comment: "400",
		view: "900K",
	},
	{
		id: "7",
		title: "Introduction to TypeScript: Why Use It?",
		tag: ["TypeScript", "JavaScript"],
		time: "5 minutes",
		like: "1.1K",
		comment: "350",
		view: "750K",
	},
	{
		id: "8",
		title: "Optimizing Web Performance: Best Practices",
		tag: ["Web Development", "Performance"],
		time: "9 minutes",
		like: "2.5K",
		comment: "900",
		view: "1.8M",
	},
	{
		id: "9",
		title: "Getting Started with GraphQL in a React App",
		tag: ["GraphQL", "React", "API"],
		time: "7 minutes",
		like: "1.4K",
		comment: "450",
		view: "1M",
	},
	{
		id: "10",
		title: "Authentication with JWT in Node.js",
		tag: ["Node.js", "Security", "Authentication"],
		time: "8 minutes",
		like: "1.7K",
		comment: "600",
		view: "1.3M",
	},
	{
		id: "11",
		title: "Building Responsive Designs with Tailwind CSS",
		tag: ["Tailwind CSS", "CSS", "Frontend"],
		time: "6 minutes",
		like: "1.6K",
		comment: "550",
		view: "1.2M",
	},
];
