import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import React from "react";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import ClientToast from "@/components/client-toast";

// const geistSans = Geist({
// 	variable: "--font-geist-sans",
// 	subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
// 	variable: "--font-geist-mono",
// 	subsets: ["latin"],
// });

export const metadata: Metadata = {
	title: "Forum",
	description: "Generated by Team Name",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await auth();
	return (
		//bg-[#05061B]
		<html lang="en" suppressHydrationWarning>
			{/* <body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			> */}
			<body className={` antialiased`} cz-shortcut-listen="true">
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<SessionProvider session={session}>
						<SidebarProvider defaultOpen={true}>
							<AppSidebar />
							<SidebarInset>{children}</SidebarInset>
							<ClientToast />
						</SidebarProvider>
					</SessionProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
